server:
  port: 8888

spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
      discovery:
        username: nacos
        password: nacos
        namespace: public

