server:
  port: 4001

spring:
  application:
    name: AliyunUpload-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        username: nacos
        password: nacos
        refresh-enabled: true
        context-path: /nacos
      discovery:
        username: nacos
        password: nacos
  config:
    import:
      - optional:nacos:aliyun-oss.yml
#aliyun:
#  bucket-name: 1
#  access-key-id: 2
#  access-key-secret: 3
#  endpoint: 4
#  url-prefix: 5
