server:
  port: 4002

spring:
  application:
    name: ShowDetails-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        username: nacos
        password: nacos
        refresh-enabled: true
        namespace: bb3ea73f-111d-4c49-a0db-efa2f1b29126
        context-path: /nacos
      discovery:
        username: nacos
        password: nacos
        namespace: bb3ea73f-111d-4c49-a0db-efa2f1b29126
  config:
    import:
      - optional:nacos:activity-database-dev.yml?namespace=dev&refreshEnabled=true


