server:
  port: 4000

spring:
  application:
    name: activity-service
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
        server-addr: 127.0.0.1:8848
        extension-configs: yaml
      discovery:
        username: nacos
        password: nacos
        namespace: bb3ea73f-111d-4c49-a0db-efa2f1b29126

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test-activity?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

